import type { TemplateOption } from "@/types/project";

export const curatedThemeFamilies: TemplateOption[] = [
  {
    id: "\uC77C\uAE30\uC7A5A",
    name: "\uC77C\uAE30\uC7A5A",
    description:
      "Diary-oriented family with balanced text, date, and gallery layouts.",
    accentColor: "#9A9088",
    coverLabel: "A4 / A5 / Square",
    theme: "\uC77C\uAE30\uC7A5A",
    bookSpecIds: ["PHOTOBOOK_A4_SC", "PHOTOBOOK_A5_SC", "SQUAREBOOK_HC"],
    templateKinds: ["cover", "content", "divider", "publish"],
    templateCount: 18,
    variants: [],
    thumbnailUrl: "/theme/diary-a.png",
  },
  {
    id: "\uC77C\uAE30\uC7A5B",
    name: "\uC77C\uAE30\uC7A5B",
    description:
      "Diary family with denser content coverage and more body template variants.",
    accentColor: "#71667C",
    coverLabel: "A4 / A5 / Square",
    theme: "\uC77C\uAE30\uC7A5B",
    bookSpecIds: ["PHOTOBOOK_A4_SC", "PHOTOBOOK_A5_SC", "SQUAREBOOK_HC"],
    templateKinds: ["cover", "content", "divider", "publish"],
    templateCount: 21,
    variants: [],
    thumbnailUrl: "/theme/diary-b.jpg",
  },
  {
    id: "\uC54C\uB9BC\uC7A5A",
    name: "\uC54C\uB9BC\uC7A5A",
    description:
      "Structured notice-book family for captions, dates, and classroom metadata.",
    accentColor: "#4C8B74",
    coverLabel: "A4 / A5 / Square",
    theme: "\uC54C\uB9BC\uC7A5A",
    bookSpecIds: ["PHOTOBOOK_A4_SC", "PHOTOBOOK_A5_SC", "SQUAREBOOK_HC"],
    templateKinds: ["cover", "content", "divider", "publish"],
    templateCount: 18,
    variants: [],
    thumbnailUrl: "/theme/notice-book-a.png",
  },
  {
    id: "\uC54C\uB9BC\uC7A5B",
    name: "\uC54C\uB9BC\uC7A5B",
    description:
      "Notice-book family with the broadest body-layout coverage across specs.",
    accentColor: "#7A8F41",
    coverLabel: "A4 / A5 / Square",
    theme: "\uC54C\uB9BC\uC7A5B",
    bookSpecIds: ["PHOTOBOOK_A4_SC", "PHOTOBOOK_A5_SC", "SQUAREBOOK_HC"],
    templateKinds: ["cover", "content", "divider", "publish"],
    templateCount: 19,
    variants: [],
    thumbnailUrl: "/theme/notice-book-b.png",
  },
  {
    id: "\uC54C\uB9BC\uC7A5C",
    name: "\uC54C\uB9BC\uC7A5C",
    description:
      "Notice-book family with cleaner rhythm and stronger divider pages.",
    accentColor: "#A66B4C",
    coverLabel: "A4 / A5 / Square",
    theme: "\uC54C\uB9BC\uC7A5C",
    bookSpecIds: ["PHOTOBOOK_A4_SC", "PHOTOBOOK_A5_SC", "SQUAREBOOK_HC"],
    templateKinds: ["cover", "content", "divider", "publish"],
    templateCount: 18,
    variants: [],
    thumbnailUrl: "/theme/notice-book-c.png",
  },
  {
    id: "\uAD6C\uAE00\uD3EC\uD1A0\uBD81A",
    name: "\uAD6C\uAE00\uD3EC\uD1A0\uBD81A",
    description:
      "Photo-forward family with strong gallery emphasis and light copy density.",
    accentColor: "#4A6FA5",
    coverLabel: "A4 / A5 / Square",
    theme: "\uAD6C\uAE00\uD3EC\uD1A0\uBD81A",
    bookSpecIds: ["PHOTOBOOK_A4_SC", "PHOTOBOOK_A5_SC", "SQUAREBOOK_HC"],
    templateKinds: ["cover", "content", "divider", "publish"],
    templateCount: 18,
    variants: [],
    thumbnailUrl: "/theme/google-photo-book-a.png",
  },
  {
    id: "\uAD6C\uAE00\uD3EC\uD1A0\uBD81B",
    name: "\uAD6C\uAE00\uD3EC\uD1A0\uBD81B",
    description:
      "Compact photo-book family with fewer but more focused body templates.",
    accentColor: "#305C8C",
    coverLabel: "A4 / A5 / Square",
    theme: "\uAD6C\uAE00\uD3EC\uD1A0\uBD81B",
    bookSpecIds: ["PHOTOBOOK_A4_SC", "PHOTOBOOK_A5_SC", "SQUAREBOOK_HC"],
    templateKinds: ["cover", "content", "divider", "publish"],
    templateCount: 15,
    variants: [],
    thumbnailUrl: "/theme/google-photo-book-b.png",
  },
  {
    id: "\uAD6C\uAE00\uD3EC\uD1A0\uBD81C",
    name: "\uAD6C\uAE00\uD3EC\uD1A0\uBD81C",
    description:
      "Photo-book family with strong image regions and balanced supporting text.",
    accentColor: "#274C77",
    coverLabel: "A4 / A5 / Square",
    theme: "\uAD6C\uAE00\uD3EC\uD1A0\uBD81C",
    bookSpecIds: ["PHOTOBOOK_A4_SC", "PHOTOBOOK_A5_SC", "SQUAREBOOK_HC"],
    templateKinds: ["cover", "content", "divider", "publish"],
    templateCount: 18,
    variants: [],
    thumbnailUrl: "/theme/google-photo-book-c.png",
  },
  {
    id: "\uACF5\uC6A9",
    name: "\uACF5\uC6A9",
    description:
      "Shared utility family used across multiple themes for common content layouts.",
    accentColor: "#6B7280",
    coverLabel: "A4 / A5 / Square",
    theme: "\uACF5\uC6A9",
    bookSpecIds: ["PHOTOBOOK_A4_SC", "PHOTOBOOK_A5_SC", "SQUAREBOOK_HC"],
    templateKinds: ["content"],
    templateCount: 3,
    variants: [],
  },
];
